version: '3.8'

services:
  etustackoverflow:
    image: ${DOCKER_REGISTRY-}etustackoverflow
    build:
      context: .
      dockerfile: EtuStackOverflow/Dockerfile
    ports:
      - "443:443"
    restart: always
    depends_on:
      - etusowf-db
    networks:
      - etu

  etusowf-db:
    image: mysql:latest
    container_name: etusowf-db
    environment:
        MYSQL_ROOT_PASSWORD: P@ssw0rd
        MYSQL_DATABASE: EtuStackOverflowDB
        MYSQL_USER: etu_user
        MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    restart: always
    networks:
      - etu
    volumes:
        - mysqldata:/var/lib/mysql

networks:
  etu:

volumes:
  mysqldata:
