version: '3.4'

services:
  c_askforetuapp:
    image: ${DOCKER_REGISTRY-}askforetu
    build:
      context: .
      dockerfile: EtuStackOverflow/Dockerfile
    ports:
      - "5004:5004"
    restart: always