version: '3.4'

services:
  # etusowf-db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: etusowf-db
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     SA_PASSWORD: "P@ssw0rd"
  #   ports:
  #     - "1433:1433"
  #   restart: always
  #   networks:
  #     - etu
  #   volumes:
  #     - mssqldata:/var/opt/mssql

  c_askforetuapp:
    image: askforetu
    build:
      context: .
      dockerfile: EtuStackOverflow/Dockerfile
    ports:
      - "5004:5004"
#     networks:
#       - etu

# networks:
#   etu:

# volumes:
#   mssqldata:
  
